bypass_cache: true
title: Support
content: |
  #Need Support?
  
  Read the FAQs below 
  
  If no answer there try the forum:
  
  <p> <a class="btn btn-primary" href="#" role="button">Forum for Teacher Virus Infected »</a></p>
  