title: Get Infected!
content: |
  <div class="jumbotron"><h1>Android</h1>
  <p><b>Step 1:</b> Download & Install Webserver - <a href="#" >DropidPHP APK</a></p>
  <p><b>Step 2:</b> Download & Install Teacher Virus - <a href="#" >Teacher Virus APK</a></p>
  <p><b>Step 3:</b> Open Teacher Virus App and follow instructions</a></p>
  </div>
  
  ##Other Devices?
  
  **Step 1:** Download & Install Webserver of your choice. 
  
  **Step 2:** Download getinfected.php to "root" of webserver public folder (e.g. htdocs, public_html or /var/www on raspberry Pi)
  
  **Step 3:** Open web browser and access that file on your webserver and follow install process.
